version: '2'

services:

  web:
    restart: always
    build: .
    environment:
      - DEBUG=False
    env_file: .env
    volumes:
      - static:/static
    network_mode: bridge


volumes:

  static:
    driver: local
