version: '2'

services:

  web:
    restart: always
    build: .
    environment:
      - DEBUG=False
    env_file: .env
    volumes:
      - static:/static
      - sqlite_data:/data


volumes:

  static:
    driver: local

  sqlite_data:
    driver: local
